language: node_js

node_js:
  - "7"

sudo: false

cache: yarn

script:
  - yarn run test:ci

after_success:
  - codecov

before_deploy:
  - react-scripts build
  - cp ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: certification-tracker-test.surge.sh
  skip_cleanup: true